use_frameworks!

platform :ios, '8.0'

target 'MB_UIButton_Example' do
  pod 'MB_UIButton', :path => '../'

  target 'MB_UIButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
